config/routes.rb
Mytestapp::Application.routes.draw do
  devise_for :users

  resources :products

  root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :expiry_date, :location, :name, :price, :product_code
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!


  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.select("products.*").paginate(:page => params[:page], :per_page => 10) 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mytestapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>

    <%= f.error_notification %>
    <%= f.input :name-%>
    <%= f.input :product_code-%>
    <%= f.input :location,:collection => ["India","Pakistan","Srilanka"],:prompt=>"Select Location"-%>
    <%= f.input :expiry_date, :input_html => { :class => "datepicker" }-%>
    <%= f.input :price-%>


  <%= link_to raw("<i class='icon-remove'></i> Close"), "#", :class => "btn", :data => { :dismiss => "modal" } -%>
  <%= f.submit  :class => "btn" -%>  
  <%= link_to "Go Back", "#", :class => 'btn go-back' %>
<% end %>

app/views/products/_list.html.erb
 <!-- <p>Logged In as <i><b>'<%#= current_user.name %>'</b></i></p> -->
<div class="alert alert-success fade in"><%= notice %></div>
<div class="row-fluid">
  <div class="span3">
    <%= link_to raw("<i class='icon-ok'></i> New Product"), new_product_path,:class=>'btn btn-primary' -%>
  </div>
  <%= link_to raw("<i class='icon-off'> Logout</i>"),  destroy_user_session_path, :method => "delete", :title => "Logout of Application" ,:class=>'btn btn-success pull-right'-%>
</div>

<%= will_paginate @products, :remote => true %>
 <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Location</th>
        <th>Expiry</th>
        <th>Price</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
     <% @products.each do |prod|  %>
        <tr>
          <td><%= prod.name.downcase %></td>
          <td><%= prod.product_code.presence ? prod.product_code : "-" %></td>
          <td><%= prod.location %></td>
          <td><%= prod.expiry_date.strftime('%d/%m/%Y') %></td>
          <td><%= prod.price%></td>
          <td><%= link_to raw("<i class='icon-edit'></i> Edit"), edit_product_path(prod.id),  :title => "Edit this Record",:class=>'btn btn-primary' -%> </td>
          <td><%= link_to raw("<i class='icon-trash'></i> Delete"), prod,  :title => "Edit this Record",method: :delete, data: { confirm: 'Are you sure?' },:class=>'btn btn-danger' -%> </td>
        </tr>
      <% end %>
</table>  

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%#= link_to 'Show', @product %> 
<%#= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="data-index">
    <%= render :partial => "list" -%> 
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%#= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Product code:</b>
  <%= @product.product_code %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @product.expiry_date %>
</p>

<p>
  <b>Location:</b>
  <%= @product.location %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>